VP-6264: Fix confirm payment request can create separate payment document
VirtoCommerce/vc-module-experience-api pull request #122
Opened 2021-03-02 11:41 UTC by AliveMen

Fix the issue with setting any payment status when calling confirmOrderPayment or cancelOrderPayment
Fix issue with new payment creation when calling confirmOrderPayment or cancelOrderPayment

2021-03-02 12:05 UTC, Vectorfield4 requested changes
Please add a unit-test.

2021-03-02 13:52 UTC, ksavosteev approved these changes

2021-03-02 20:05 UTC, eMazeika approved these changes

2021-03-03 07:04 UTC, Vectorfield4 approved these changes

2021-03-03 07:06 UTC, merged