PT-90: add batch items mutation
VirtoCommerce/vc-module-experience-api pull request #124
Opened 2021-03-09 16:10 UTC by ksavosteev

2021-03-09 16:45 UTC, Vectorfield4 requested changes

2021-03-09 16:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
> +        public virtual async Task<CartAggregate> AddItemsAsync(ICollection<NewCartItem> newCartItem)
1. newCartItem**s**;
2. IReadOnlyCollection is better IMHO.

2021-03-09 16:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputAddItemsType.cs
> +            Field<NonNullGraphType<ListGraphType<InputNewCartItemType>>>("AddCartItems");
Just `CartItems`.

2021-03-09 16:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Schemas/InputNewCartItemType.cs
> +            Field(x => x.ProductId, false).Description("Product Id");
Add caption `nullable:`, please.

2021-03-09 16:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs
> +            ///         "addCartItems": [{
Just `cartItems`.

2021-03-09 16:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Commands/AddCartItemsCommandHandler.cs
> +        public override async Task<CartAggregate> Handle(AddCartItemsCommand request, CancellationToken cancellationToken)
Add verify test, please.

2021-03-10 09:10 UTC, AliveMen approved these changes

2021-03-10 09:15 UTC, Vectorfield4 approved these changes

2021-03-10 09:22 UTC, Vectorfield4 approved these changes

2021-03-10 09:27 UTC, merged