PT-414: Allow to pass response groups as additional parameter in CartProductService.GetCartProductsByIdsAsync
VirtoCommerce/vc-module-experience-api pull request #132
Opened 2021-03-16 08:29 UTC by akak1977

https://virtocommerce.atlassian.net/browse/PT-413

2021-03-16 08:37 UTC, ksavosteev requested changes

2021-03-16 08:37 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
> +        public async Task<IEnumerable<CartProduct>> GetCartProductsByIdsAsync(CartAggregate cartAggr, string[] ids, string additionalResponseGroups = null)
Change interface signature

2021-03-16 09:04 UTC, eMazeika approved these changes

2021-03-16 10:05 UTC, ksavosteev approved these changes

2021-03-16 14:20 UTC, Vectorfield4 requested changes

2021-03-16 14:20 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
> +            var itemResponseGroups = ItemResponseGroup.ItemAssets | ItemResponseGroup.ItemInfo | ItemResponseGroup.Outlines | ItemResponseGroup.Seo;
Should we rename this variable to `defaultResponseGroups`?

2021-03-16 14:20 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.XPurchase/Services/ICartProductService.cs
> +        Task<IEnumerable<CartProduct>> GetCartProductsByIdsAsync(CartAggregate cartAggr, string[] ids, string additionalResponseGroups = null);
Should we remove the default parameter?

2021-03-17 06:31 UTC, eMazeika approved these changes

2021-03-17 06:31 UTC, eMazeika commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartProductService.cs
> +                defaultResponseGroups |= EnumUtility.SafeParseFlags(additionalResponseGroups, ItemResponseGroup.ItemLarge);
there is no need to fallback to ItemLarge. ItemAssets as default value should be enough

2021-03-17 09:49 UTC, ksavosteev approved these changes

2021-03-17 09:49 UTC, Vectorfield4 approved these changes

2021-03-17 09:49 UTC, akak1977 commented on src/XPurchase/VirtoCommerce.XPurchase/Services/ICartProductService.cs
> +        Task<IEnumerable<CartProduct>> GetCartProductsByIdsAsync(CartAggregate cartAggr, string[] ids, string additionalResponseGroups = null);
We decided to keep this

2021-03-17 09:54 UTC, merged