PT-2233: Fix outline titles for categories/products
VirtoCommerce/vc-module-experience-api pull request #169
Opened 2021-06-16 08:31 UTC by akak1977

https://virtocommerce.atlassian.net/browse/PT-2232

2021-06-16 09:19 UTC, eMazeika reviewed
PageTitle is optional while SemanticUrl is required. Why not use both: PageTitle ?? SemanticUrl ?? ...

2021-06-16 09:21 UTC, Vectorfield4 approved these changes

2021-06-16 13:32 UTC, akak1977 commented
> PageTitle is optional while SemanticUrl is required. Why not use both: PageTitle ?? SemanticUrl ?? ...

No info in the issue about such resolution. Just "page title" or "name" in case of absence.

2021-06-17 08:18 UTC, tatarincev requested changes

2021-06-17 08:18 UTC, tatarincev commented on src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/OutlineExtensions.cs
> +                    Title = item.SeoInfos?.FirstOrDefault()?.PageTitle ?? item.Name,
You must respect the passed  `culture name`  to choose a proper seoInfos object that best matched it, also, you can use this extension https://github.com/VirtoCommerce/vc-module-experience-api/blob/dev/src/VirtoCommerce.ExperienceApiModule.Core/Extensions/IHasLanguageExtensions.cs for that.

2021-06-17 09:42 UTC, merged