PT-5954: Can't extend Orders connection handler in XAPI
VirtoCommerce/vc-module-experience-api pull request #259
Opened 2021-12-19 07:35 UTC by BelyakovSergey

## Description
Can't extend Orders connection handler in XAPI
## References
### QA-test:
### Jira-link:
https://virtocommerce.atlassian.net/browse/PT-5954
### Artifact URL:

2021-12-20 06:31 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
> +            query.Map(context);
Create extension. Consider moving Line 180 inside thisextension.
```suggestion
            var query = context.ExtractQuery<SearchOrderQuery>();
```

2021-12-20 06:32 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/QueryConnectionArguments.cs
> +        public QueryConnectionArguments AddArguments(QueryArguments arguments)
```suggestion
        public virtual QueryConnectionArguments AddArguments(QueryArguments arguments)
```

2021-12-20 06:35 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
> +            orderConnectionBuilder.FieldType.Arguments = AbstractTypeFactory<QueryConnectionArguments>.TryCreateInstance().AddArguments(orderConnectionBuilder.FieldType.Arguments);
Hide second line with an extension. You have all data to make it.
```suggestion
            var orderConnectionBuilder = GraphTypeExtenstionHelper
                .CreateConnection<CustomerOrderType, object>()
                .Name("orders")
                .PageSize(20)
                .Arguments<QueryConnectionArguments>();
```

2021-12-20 11:56 UTC, Vectorfield4 approved these changes

2021-12-20 15:17 UTC, ksavosteev requested changes

2021-12-20 15:17 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/QueryConnectionArguments.cs
> +    public class QueryConnectionArguments : ArgumentList
rename to OrderQueryConnectionArguments

2021-12-20 15:17 UTC, ksavosteev commented on src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/ISearchOrderQuery.cs
> +    public interface ISearchOrderQuery
rename to IExtendableQuery
move to Core

2021-12-20 15:17 UTC, ksavosteev commented on src/VirtoCommerce.ExperienceApiModule.Core/Infrastructure/ISearchOrderQuery.cs
> +        public void Map(IResolveConnectionContext<object> context);
use IResolveFieldContext

2021-12-21 09:43 UTC, ksavosteev approved these changes

2021-12-22 07:32 UTC, merged