Fix User1 without contact has access to user2's cart
VirtoCommerce/vc-module-experience-api pull request #328
Opened 2022-07-14 14:44 UTC by Andalexshap

## Description
User1 without contact has access to user2's cart

## References
### QA-test:
### Jira-link:
### Artifact URL:

2022-07-18 10:54 UTC, ksavosteev requested changes

2022-07-18 10:54 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Authorization/CanAccessCartAuthorizationRequirement .cs
> +                        searchQuery.UserId = currentUserId;
refactor with only one `break` at the end of case

2022-07-20 09:57 UTC, ksavosteev approved these changes

2022-07-21 14:23 UTC, Vectorfield4 approved these changes

2022-07-25 07:16 UTC, merged