Adding an access request when a user creates an order
VirtoCommerce/vc-module-experience-api pull request #330
Opened 2022-07-15 19:04 UTC by Andalexshap

## Description
Before creating an order, user access is checked
## References
### QA-test:
### Jira-link:
### Artifact URL:

2022-07-17 12:45 UTC, Vectorfield4 requested changes

2022-07-17 12:45 UTC, Vectorfield4 commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Schemas/OrderSchema.cs
> +        public OrderSchema(IMediator mediator, ICurrencyService currencyService, IAuthorizationService authorizationService, ICustomerOrderService customerOrderService, IShoppingCartService cartServi
Use mediator, instead of extending ctor.

2022-07-22 10:47 UTC, ksavosteev requested changes

2022-07-22 10:47 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.ExperienceApiModule.XOrder/Authorization/CanAccessOrderAuthorizationHandler.cs
> +                    result = cart.CustomerId == currentUserId || currentUserId == null;
need to check that cart `IsAnonymous` is true when `currentUserId` is null

2022-07-25 09:04 UTC, ksavosteev approved these changes

2022-08-03 14:00 UTC, Vectorfield4 approved these changes

2022-08-03 14:02 UTC, merged