PT-5417 Do not calculate taxes if Enable Tax Calculation is disabled …
VirtoCommerce/vc-module-experience-api pull request #334
Opened 2022-08-07 17:03 UTC by Andalexshap

…in Store settings

## Description

## References
### QA-test:
### Jira-link:
### Artifact URL:

2022-08-08 04:17 UTC, akak1977 approved these changes

2022-08-08 08:07 UTC, ksavosteev requested changes

2022-08-08 08:07 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
>              }
check Store.TaxEvaluationEnabled setting before getting taxProvider

2022-08-08 08:07 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Extensions/ServiceCollectionExtensions.cs
> +            services.AddTransient<SettingsExtensions>();
Remove

2022-08-08 08:07 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
> +                var taxRates = new List<TaxRate>();
User cartAggr.Store to get stroe settings
if TaxCalculationEnabled == false there's not need to even get `taxProvider` and `ApplyTaxRates`

2022-08-08 08:07 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
> +                var taxRates = new List<TaxRate>();
User cartAggr.Store to get stroe settings
if TaxCalculationEnabled == false there's not need to even get `taxProvider` and `ApplyTaxRates`

2022-08-12 13:22 UTC, ksavosteev reviewed
Inject StoreService into EvalProductsTaxMiddleware and check TaxEnabled setting

2022-08-12 13:22 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/Services/CartAvailMethodsService.cs
> +        protected async Task<TaxProvider> GetActiveTaxProviderAsync(CartAggregate cartAggregate)
Add a new overloaded method instead
make the old one Obsolete

2022-08-12 13:22 UTC, ksavosteev commented on src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
> +            if (!await _crudStoreService.GetSettingValue<bool>(Cart.StoreId, StoreSetting.TaxCalculationEnabled))
Use Store property

2022-08-12 13:22 UTC, ksavosteev commented on src/VirtoCommerce.ExperienceApiModule.Core/Extensions/StoreServiceExtensions.cs
> +    public static class StoreServiceExtensions
Remove this class

2022-08-12 14:35 UTC, ksavosteev approved these changes

2022-08-17 16:03 UTC, merged