PT-8543 "Get all carts" request authorization rules failed (XAPI)
VirtoCommerce/vc-module-experience-api pull request #335
Opened 2022-08-08 07:57 UTC by Andalexshap

## Description
if searchQuery contains UserId = User_1:
     1) User_1 : Access allowed for Cart_1
     2) Anonymous : Access allowed for Cart_1
     3) User_2: Access denied for Cart_1
if searchQuery does not contain UserId:
     1) User_1 : Access allowed for Cart_1
     2) Anonymous : Access denied for Cart_1
     3) User_2: Access allowed for Cart_2

## References
### QA-test:
### Jira-link:
### Artifact URL:

2022-08-08 08:40 UTC, akak1977 approved these changes

2022-08-08 11:04 UTC, ksavosteev requested changes
fix unit tests

2022-08-09 07:39 UTC, akak1977 approved these changes

2022-08-09 07:39 UTC, ksavosteev approved these changes

2022-08-09 11:56 UTC, merged