VCST-396: Improve EvalProductsInventoryMiddleware extensibility
VirtoCommerce/vc-module-experience-api pull request #522
Opened 2024-01-31 19:14 UTC by OlegoO

## Description
feat: Improved EvalProductsInventoryMiddleware extensibility. Added GetInventorySearchCriteria virtual method for configuring the search criteria and added IGenericPipelineLauncher call to GenericPipelineLauncher like for EvalProductsPricesMiddleware.

## References
### QA-test:
### Jira-link:

https://virtocommerce.atlassian.net/browse/VCST-396
### Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_3.803.0-pr-522-81ec.zip

2024-01-31 19:21 UTC, artem-dudarev requested changes

2024-01-31 19:21 UTC, artem-dudarev commented on src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
> +        protected virtual async Task<InventorySearchCriteria> GetInventorySearchCriteria(string[] productIds, int pageSize, int skip)
`IList<string> productIds, int skip, int take`

2024-02-01 09:57 UTC, OlegoO commented on src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
> +                    var searchCriteria = await GetInventorySearchCriteria(productIds, pageSize, skip);
Fixed

2024-02-01 10:20 UTC, ksavosteev requested changes

2024-02-01 10:20 UTC, ksavosteev commented on src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Middlewares/EvalProductsInventoryMiddleware.cs
> +            var searchCreteria = AbstractTypeFactory<InventorySearchCriteria>.TryCreateInstance();
typo, change to searchCriteria

2024-02-01 10:29 UTC, ksavosteev approved these changes

2024-02-01 10:34 UTC, artem-dudarev approved these changes

2024-02-05 15:47 UTC, merged